name: GoLive Script Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.7'
      - name: Run version check
        run: go version
      - name: Install Dependencies
        id: InstallDeps
        run: |
          go get github.com/go-check/check
          go get github.com/go-sql-driver/mysql
          go get github.com/gorilla/mux
          go get github.com/satori/go.uuid
          go get golang.org/x/crypto/bcrypt
      - if: ${{success()}}
        name: Test Go Check
        run: |
          go test -v./script_test.go          
      - if: ${{failure()}}
        name: Create Issues
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}
